sudo: required
services:
  - docker
addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server
language: ruby
env:
  - DOCKER_COMPOSE_VERSION=1.22.0
before_install:
#    - sudo /etc/init.d/mysql stop
    - docker version
    - docker-compose version
#    - docker-compose --file docker-compose.yml up --build --detach 
    - docker-compose up --detach --build
    - mysql --host 127.0.0.1 --port  3307 -uroot -e 'status;'
    - mysql --host 127.0.0.1 --port  3308 -uroot -e 'status;'
    - mysql --host 127.0.0.1 --port 53306 -uroot -e 'status;'

script:
#    - which mysql
#    - mysql -V
#    - mysql --host 127.0.0.1 --port  3306 -uroot -e 'status;'
#    - mysql --host 127.0.0.1 --port 53306 -uroot -e 'status;'
    - ruby -v
