version: '3'
services:
#  mysqld8:
#    container_name: mysqld8
#    hostname: db
#    image: mysql:8
#    restart: always
##    build: ./mysql
#    environment:
#      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#      MYSQL_ROOT_PASSWORD: tiger
##      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      MYSQL_DATABASE: test
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    ports:
#      - 53306:53306
#
  mysqld57:
    container_name: mysqld57
    hostname: mysql57
    image: mysql:5.7.22
    restart: always
    build: ./mysqld57
    ports:
      - 3306:3306

#  adminer:
#    container_name: adminer
#    hostname: adminer
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
