version: '3'
services:
  mysqld55:
    container_name: mysqld55
    hostname: mysql55
    image: mysql:5.5
    restart: always
    build: ./mysqld55
    ports:
      - 3307:3306
  mysqld57:
    container_name: mysqld57
    hostname: mysql57
    image: mysql:5.7
    restart: always
    build: ./mysqld57
    ports:
      - 3308:3306
  mysqld80:
    container_name: mysqld80
    hostname: mysqld80
    image: mysql:8.0
    restart: always
    build: ./mysqld80
    ports:
      - 53306:3306
#  adminer:
#    container_name: adminer
#    hostname: adminer
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
