# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:

      - checkout

      - setup_remote_docker:
          # version: 17.05.0-ce
          docker_layer_caching: true
      - run: docker version
      - run: docker-compose version
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
          environment:
            DOCKER_COMPOSE_VERSION: 1.22.0

      - run: docker version
      - run: docker-compose version
      - run:
          name: Eexecute docker-compose
          command: |
            docker-compose up  --build --detach


